name: Secret Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  secret-scan:
    name: Scan for Secrets
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run Gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITLEAKS_LICENSE: ${{ secrets.GITLEAKS_LICENSE }}

    - name: Scan for hardcoded patterns
      run: |
        echo "🔍 Scanning for hardcoded credentials..."

        # Check for common credential patterns
        if grep -r -i "password\s*=" --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" src/; then
          echo "❌ Found hardcoded password references"
          exit 1
        fi

        if grep -r -i "api_key\s*=" --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" src/; then
          echo "❌ Found hardcoded API key references"
          exit 1
        fi

        if grep -r -i "secret\s*=" --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" src/; then
          echo "❌ Found hardcoded secret references"
          exit 1
        fi

        # Check for JWT tokens that might be hardcoded
        if grep -r "eyJ[A-Za-z0-9-_=]*\." --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" src/ | grep -v "test" | grep -v "mock"; then
          echo "❌ Found potential hardcoded JWT tokens"
          exit 1
        fi

        # Check for URL patterns that might contain credentials
        if grep -r "https://[^/]*:[^/]*@" --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" src/; then
          echo "❌ Found URLs with embedded credentials"
          exit 1
        fi

        echo "✅ No hardcoded credentials found"

    - name: Check environment variable usage
      run: |
        echo "🔍 Checking environment variable patterns..."

        # Ensure no fallback values for sensitive data
        if grep -r "process\.env\.[A-Z_]*.*||" --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" src/ | grep -i -E "(key|secret|password|token)"; then
          echo "❌ Found environment variables with fallback values for sensitive data"
          exit 1
        fi

        echo "✅ Environment variable patterns look good"