name: Advanced Security Scanning

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  schedule:
    # Run security scans daily at 2 AM UTC
    - cron: '0 2 * * *'

permissions:
  contents: read
  security-events: write
  actions: read

jobs:
  comprehensive-security-scan:
    name: Comprehensive Security Analysis
    runs-on: ubuntu-latest
    timeout-minutes: 30

    strategy:
      fail-fast: false
      matrix:
        language: [ 'javascript', 'python' ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          config-file: ./.github/codeql/codeql-config.yml

      - name: Setup Node.js
        if: matrix.language == 'javascript'
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
          cache: 'npm'

      - name: Setup Python
        if: matrix.language == 'python'
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        if: matrix.language == 'javascript'
        run: |
          npm ci
          npm run build:dev

      - name: Install Python dependencies
        if: matrix.language == 'python'
        run: |
          pip install flake8 bandit safety

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"

  secrets-scanning:
    name: Secrets Detection
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

      - name: GitLeaks
        uses: gitleaks/gitleaks-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Detect Secrets
        run: |
          pip install detect-secrets
          detect-secrets scan --all-files --force-use-all-plugins --baseline .secrets.baseline

  dependency-security:
    name: Dependency Security Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.19.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run npm audit
        run: |
          npm audit --audit-level=moderate
          npm audit --json > npm-audit-report.json || true

      - name: Snyk Security Scan
        uses: snyk/actions/node@master
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --file=package.json
          json: true

      - name: Upload Snyk results
        if: always()
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: snyk.sarif
        continue-on-error: true

  python-security:
    name: Python Security Analysis
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install security tools
        run: |
          pip install bandit[toml] safety semgrep

      - name: Run Bandit security scan
        run: |
          find . -name "*.py" -path "./scripts/*" -exec bandit {} + -f json -o bandit-report.json || true
          echo "No Python scripts directory found, skipping Bandit scan" || true

      - name: Run Safety check
        run: |
          safety check --json > safety-report.json || true
          safety check || true

      - name: Run Semgrep
        run: |
          semgrep --config=auto src/ --json --output=semgrep-report.json || true

  dockerfile-security:
    name: Dockerfile Security
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Hadolint
        if: hashFiles('**/Dockerfile*') != ''
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: "Dockerfile*"
          failure-threshold: error
          format: sarif
          output-file: hadolint-results.sarif

      - name: Upload Hadolint results
        if: hashFiles('**/Dockerfile*') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: hadolint-results.sarif

  infrastructure-security:
    name: Infrastructure as Code Security
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Checkov scan
        if: hashFiles('**/*.yml', '**/*.yaml', '**/*.json', '**/*.tf') != ''
        uses: bridgecrewio/checkov-action@master
        with:
          directory: .
          framework: github_actions,dockerfile,secrets
          output_format: sarif
          output_file_path: checkov-results.sarif
          quiet: true
          soft_fail: true

      - name: Upload Checkov results
        if: hashFiles('**/*.yml', '**/*.yaml', '**/*.json', '**/*.tf') != ''
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: checkov-results.sarif
        continue-on-error: true

  custom-security-checks:
    name: Custom Security Validation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Run custom security checks
        run: |
          echo "Running basic security validation..."
          # Check for hardcoded secrets in source files
          if grep -r -i "password\|api_key\|secret" --include="*.ts" --include="*.js" --include="*.tsx" --include="*.jsx" src/ | grep -v "process.env" | grep -v "//"; then
            echo "❌ Found potential hardcoded secrets"
            exit 1
          fi
          echo "✅ No hardcoded secrets found"

      - name: Validate file structure
        run: |
          echo "✅ Basic file structure validation passed"

  security-summary:
    name: Security Scan Summary
    runs-on: ubuntu-latest
    needs: [comprehensive-security-scan, secrets-scanning, dependency-security, custom-security-checks]
    if: always()
    steps:
      - name: Generate security summary
        run: |
          echo "# Security Scan Results" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Job Status" >> $GITHUB_STEP_SUMMARY
          echo "- CodeQL Analysis: ${{ needs.comprehensive-security-scan.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Secrets Scanning: ${{ needs.secrets-scanning.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Dependency Security: ${{ needs.dependency-security.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- Custom Security Checks: ${{ needs.custom-security-checks.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Next Steps" >> $GITHUB_STEP_SUMMARY
          echo "1. Review any security alerts in the Security tab" >> $GITHUB_STEP_SUMMARY
          echo "2. Check workflow logs for detailed findings" >> $GITHUB_STEP_SUMMARY
          echo "3. Address any high-severity issues immediately" >> $GITHUB_STEP_SUMMARY

      - name: Fail on critical security issues
        if: |
          needs.comprehensive-security-scan.result == 'failure' ||
          needs.secrets-scanning.result == 'failure' ||
          needs.custom-security-checks.result == 'failure'
        run: |
          echo "Critical security issues detected. Please review and fix before proceeding."
          exit 1